image:
- Visual Studio 2017

install:
- cmd: nuget restore RockMargin.sln
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
- ps: Vsix-IncrementVsixVersion -versionType revision | Vsix-UpdateBuildVersion

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

configuration: Release
platform: Any CPU

build:
  project: RockMargin.sln
  verbosity: minimal

after_build:
- ps: Push-AppveyorArtifact RockMargin\bin\Release\RockMargin.vsix -FileName "RockMargin-v$($env:APPVEYOR_BUILD_VERSION).vsix"