version: 0.0.{build}
image:
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013
configuration: Release
platform: Any CPU
before_build:
- nuget restore -Verbosity quiet
build:
  project: RockMargin.sln
  verbosity: minimal